apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-system
resources:
  - litellm/namespace.yaml
  - litellm/configmap.yaml
  - litellm/deployment.yaml
  - litellm/service.yaml
  - litellm/hpa.yaml
  - litellm/servicemonitor.yaml
